car:
    resource: "@CarBundle/Controller/"
    type:     annotation
    prefix:   /

#acme_demo:
#    resource: "@AcmeDemoBundle/Resources/config/routing.xml"
#    prefix:   /

app:
    resource: '@AppBundle/Controller/'
    type: annotation

user:
    resource: '@UserBundle/Controller'
    type: annotation
    prefix: /

#user_registration:
#    path:     /register
#    defaults: { _controller: UserBundle:Registration:register }

#fos_user_security:
#    resource: "@UserBundle/Resources/config/routing/security.xml"
#
#fos_user_profile:
#    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
#    prefix: /profile
#
#fos_user_register:
#    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
#    prefix: /register
#
#fos_user_resetting:
#    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
#    prefix: /login
#
#fos_user_change_password:
#    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
#    prefix: /profile
