# app/config/security.yml
security:
    encoders:
        UserBundle\Entity\User:
              algorithm: bcrypt
#        FOS\UserBundle\Model\UserInterface: bcrypt
#         Symfony\Component\Security\Core\User\User: plaintext

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

#    providers:
#        userbundle:
#            id: fos_user.user_provider.username

    providers:
        in_memory:
            memory: ~

    firewalls:
        main:
            pattern: ^/
            form_login:
#                provider: fos_userbundle
                #form.csrf_provider: security.csrf.token_manager # Use form.csrf_provider instead for Symfony <2.4
            logout:       true
            anonymous:    true

    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/, role: ROLE_ADMIN }




